version: '3'
services:
  CoreApp:
    build: .
    environment:
     - ASPNETCORE_CoreApp_DatabaseProvider=${ASPNETCORE_CoreApp_DatabaseProvider}
     - ASPNETCORE_CoreApp_ConnectionString=${ASPNETCORE_CoreApp_ConnectionString}
    ports:
     - "5000:5000"
